github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
   
name: "cod(ex).python"
markdown: kramdown
theme: jekyll-theme-modernist

permalink: /blog/:year/:month/:day/:title
